### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BrianDuncan-HatTrick** [andremion/CounterFab#12]
I just loaded the recent Android update and I am getting this error.

Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
    java.lang.RuntimeException
 at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1850)
        at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1967)
        at android.graphics.drawable.RippleDrawable$RippleState.<init>(RippleDrawable.java:997)
        at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:988)
        at android.graphics.drawable.RippleDrawable.createConstantState(RippleDrawable.java:986)
        at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1774)
        at android.graphics.drawable.RippleDrawable.mutate(RippleDrawable.java:974)
        at android.view.View.applyBackgroundTint(View.java:20601)
        at android.view.View.setBackgroundDrawable(View.java:20472)
        at android.support.design.widget.FloatingActionButton.access$001(FloatingActionButton.java:69)
        at android.support.design.widget.FloatingActionButton$ShadowDelegateImpl.setBackgroundDrawable(FloatingActionButton.java:862)
        at android.support.design.widget.FloatingActionButtonLollipop.setBackgroundDrawable(FloatingActionButtonLollipop.java:73)
        at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:188)
        at com.andremion.counterfab.CounterFab.<init>(CounterFab.java:90)
        at com.andremion.counterfab.CounterFab.<init>(CounterFab.java:86)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.hattrick.aformula4success.ordering.Home.onCreate(Home.java:87)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by andremion** [comment]
Hi @shirleyarmendariz,

I can't reproduce this.

Could you send me more details about it? Such as:
- Android version
- When this occurs

Thanks

**Comment by Eng-MahmoudBasuony** [comment]
haw to change color Background **Badge** count on Floating action button

**Comment by andremion** [comment]
@Eng-MahmoudBasuony, It was released, please see the latest version

**Comment by Eng-MahmoudBasuony** [comment]
I’m really grateful
