### ISSUE TITLE
Crash on Android 5.0

### ISSUE THREAD

**Issue by sebaslogen** [andremion/CounterFab#25]
Crash on Android 5.0, ZenPad S 8.0 (Z580CA)
This comes from a production user so I don't have an exact reproduction scenario but other versions of Android from the same app haven't reproduced this crash so far.
CountraFab version 1.1.1

Crash log
```
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Parcel;Ljava/lang/ClassLoader;)V in class Landroid/view/View$BaseSavedState; or its super classes (declaration of 'android.view.View$BaseSavedState' appears in /system/framework/framework.jar:classes2.dex)
       at com.andremion.counterfab.CounterFab$SavedState.<init>(CounterFab.java:281)
       at com.andremion.counterfab.CounterFab$SavedState.<init>(CounterFab.java:257)
       at com.andremion.counterfab.CounterFab$SavedState$1.createFromParcel(CounterFab.java:306)
       at com.andremion.counterfab.CounterFab$SavedState$1.createFromParcel(CounterFab.java:302)
       at android.os.Parcel.readParcelable(Parcel.java:2244)
       at android.os.Parcel.readValue(Parcel.java:2146)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
       at android.os.Parcel.readSparseArray(Parcel.java:1868)
       at android.os.Parcel.readValue(Parcel.java:2203)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1361)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1526)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1497)
       at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:197)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1684)
       at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3774)
       at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:120)
       at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:405)
       at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:387)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
       at com.myapp.MainActivity.onCreate(MainActivity.kt:59)
       at android.app.Activity.performCreate(Activity.java:5975)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
       at android.app.ActivityThread.access$800(ActivityThread.java:147)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**Comment by andremion** [comment]
It's released in `1.2.0` version.
Sorry by the inconvenience.
I found that some states needed to be handle different in versions prior Nougat.

**Comment by haque023** [comment]
is there any solution is available

**Comment by andremion** [comment]
> is there any solution is available

@haque023 The [1.2.0](https://github.com/andremion/CounterFab/releases/tag/v1.2.0) version solves that issue.
The current library version is [1.2.2](https://github.com/andremion/CounterFab/releases/tag/v1.2.2)
